// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI49MI3vaqTs6lDD3BVReZmAinpbM5IXU',
    appId: '1:681616448954:web:9fd8a9a665cb040d8b5183',
    messagingSenderId: '681616448954',
    projectId: 'biosyncapp',
    authDomain: 'biosyncapp.firebaseapp.com',
    storageBucket: 'biosyncapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHUIBYpiBshUcI_W1fgc3mWdZ28Ovu5Wg',
    appId: '1:681616448954:android:da535429ce562c478b5183',
    messagingSenderId: '681616448954',
    projectId: 'biosyncapp',
    storageBucket: 'biosyncapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbJ7UbUVPVo7tmaHL1Ay7FT0UgRizHxbQ',
    appId: '1:681616448954:ios:7f94c5fdf023fb2b8b5183',
    messagingSenderId: '681616448954',
    projectId: 'biosyncapp',
    storageBucket: 'biosyncapp.firebasestorage.app',
    iosBundleId: 'com.example.bioSync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbJ7UbUVPVo7tmaHL1Ay7FT0UgRizHxbQ',
    appId: '1:681616448954:ios:7f94c5fdf023fb2b8b5183',
    messagingSenderId: '681616448954',
    projectId: 'biosyncapp',
    storageBucket: 'biosyncapp.firebasestorage.app',
    iosBundleId: 'com.example.bioSync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAI49MI3vaqTs6lDD3BVReZmAinpbM5IXU',
    appId: '1:681616448954:web:6644e40654afd1b28b5183',
    messagingSenderId: '681616448954',
    projectId: 'biosyncapp',
    authDomain: 'biosyncapp.firebaseapp.com',
    storageBucket: 'biosyncapp.firebasestorage.app',
  );
}
